language: python
os: 
  - osx
before_install:
  - brew update
  - brew install python --framework
  - brew install gfortran
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nikola build
