language: python

before_install:
  - sudo apt-get update -y
  - sudo apt-get install haskell-platform
  - cabal update
  - cabal install pandoc
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nikola build
