language: python
before_install:
- export PATH="$HOME/pandoc:$PATH"
- mkdir $HOME/pandoc
- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- pandoc --version
- rm pandoc-1.12.3.zip
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nikola build
after_success: ./travis_deploy.sh
env:
  global:
  - secure: H9DqpQrfkTorAGv9UNVEMt8A+rLuNGTC2fskrz17wx0lW5dKiHAD10nS68JImJhPbQ9+cI0M5XF9EiF8Wv/4OaZpj/63bKq7W9UYXgHDM/ObUVkMOHhXbYofPMeq7Pb24UQc+riiLFGe+qlq6LCa+pgY5Ccw1Z/p/rbvT+KRlPE=
