language: python

before_install:
  - apt-get update
  - apt-get install libpython-dev
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nikola build
